mod chunk;
mod compiler;
mod error;
mod frontend;
mod hashtable;
mod object;
mod opcode;
mod precedence;
mod repl;
mod run;
mod scanner;
mod stack;
mod token;
mod types;
mod value;
mod vm;

pub use chunk::*;
pub use compiler::*;
pub use error::*;
pub use hashtable::RoxMap;
pub use hashtable::Table;
pub use object::*;
pub use opcode::OpCode;
pub use precedence::Precedence;
pub use repl::Repl;
pub use run::*;
pub use scanner::Scanner;
pub use stack::Stack;
pub use token::*;
pub use value::*;
pub use vm::*;

pub static DEBUG_MODE: bool = false;
pub const STACK_MAX: usize = 256;
